import {
    BadgeCheck,
    Building2,
    ChartSpline,
    ClipboardList,
    Flag,
    Folders,
    FolderTree,
    Image as ImageIcon,
    IndianRupee,
    Megaphone,
    Package,
    ScrollText,
    Shield,
    TriangleAlert,
    UserRound,
    Users,
    type LucideIcon,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
    analytics: ChartSpline,
    banners: ImageIcon,
    ads: Megaphone,
    roles: Shield,
    users: Users,
    categories: FolderTree,
    "sub-categories": Folders,
    cities: Building2,
    reports: ClipboardList,
    revenue: IndianRupee,
    packages: Package,
    subscriptions: BadgeCheck,
    flags: Flag,
    logs: ScrollText,
    alerts: TriangleAlert,
    profile: UserRound,
};
